### ISSUE TITLE
Middleware does not allow for other middleware

### ISSUE THREAD

**Issue by lamebear** [PropelAuth/nextjs#25]
The way the the middleware is written doesn't allow for other middleware to be used. If I want to add any other middleware, that then has to be added to the individual routes.

Is there a way with the current implementation to use additional middleware with `authMiddleware`?

**Comment by andrew-propelauth** [comment]
Hey @lamebear, this is unfortunately something we consider to be a limitation of Next.js. Our hope is that this is something that either Next.js or a separate library solves, because at the moment, most middleware we see either doesn't support it or supports it in limited ways.
