### ISSUE TITLE
Missing repository license

### ISSUE THREAD

**Issue by stevencrake-nscale** [PropelAuth/nextjs#39]
Hi there,

I noted when collating all licenses of my package dependencies that his repo does not have a license file associated. Other PropelAuth repositories do, such as https://github.com/PropelAuth/react/blob/main/LICENSE. Without a licence, it’s unclear how others can use or contribute to the project.

Thank you for your attention to this matter. I look forward to your response.

**Comment by andrew-propelauth** [comment]
Thanks for the heads up! Looks like we didn't set up the license in this repo initially. It (and all our client libraries) are MIT Licensed, just updated the repo as well. Thanks again!

**Comment by stevencrake-nscale** [comment]
Great, thanks Andrew
