### ISSUE TITLE
Support for NextJS 15

### ISSUE THREAD

**Issue by fred3105** [PropelAuth/nextjs#44]
Hey, 

Trying to move my project to NextJS 15, I'm running the latest version 0.1.11 of @propelauth/nextj, it only supports Next13 and Next14

Is support for Next15 on the timeline ?
Thank you in advance

**Comment by andrew-propelauth** [comment]
Hey - apologies for the delay in closing this. v0.2.1 and forward have support for Next15, and [our docs](https://docs.propelauth.com/reference/fullstack-apis/nextjsapp/installation-and-setup) have been updated to reflect any differences.

The main thing to note is there are now async versions of the route handler functions (app/api/auth/[slug]/route.ts):
```
export const GET = routeHandlers.getRouteHandlerAsync
export const POST = routeHandlers.postRouteHandlerAsync
```
